### ISSUE TITLE
Could not find binary for OS 'linux' and architecture 'armv7l'.

### ISSUE THREAD

**Issue by Tankdoz** [virtualzone/onedrive-uploader#1]
I would like to run this headless on a Raspberry Pi 4, but there seems to be no binary for armv71. 

Also, not so much an issue but rather a feature request: could you make it so that login can be done fully headless, without the use of a machine with a webbrowser?

**Comment by virtualzone** [comment]
On a Raspberry Pi 4, you can use the pre-built ARM64 binary.

The login can't be done fully headless, as it requires human interaction with Microsoft's sign in.

**Comment by virtualzone** [comment]
I've been wrong: As armv7l is 32 bit, I've added this missing architecture to the installer script. Thanks for the hint.
