### ISSUE TITLE
Can not Login

### ISSUE THREAD

**Issue by tlehletmt** [virtualzone/onedrive-uploader#16]
Hi, I have the problem that i could not login. I get the Error "received unexpected status code 401"

![image](https://user-images.githubusercontent.com/109284141/192819589-6e54d129-ea05-4863-80bc-6c2266544303.png)

My Azure App:

![image](https://user-images.githubusercontent.com/109284141/192819759-bfae5659-fb1d-4c39-b715-627179f08cf9.png)
![image](https://user-images.githubusercontent.com/109284141/192820082-4024b092-4bec-4325-8ec8-4fc931adf793.png)

JSON:
![image](https://user-images.githubusercontent.com/109284141/192820269-5db6e9d5-cfdb-4497-bb23-4d7f02acd00c.png)

Browser:
![image](https://user-images.githubusercontent.com/109284141/192820470-04de58d2-402d-45e9-8389-74c88d577eca.png)

Can you give me a hint what I configured wrong?

**Comment by virtualzone** [comment]
Hi @tlehletmt, I've tried to reproduce your issue. I'm encountering a 401 error like yours when I'm using an incorrect Secret Value in "client_secret". Please make sure you're using the Secret's Value, not the ID (see screenshot below).

<img width="1042" alt="Screenshot 2022-09-28 at 19 18 40" src="https://user-images.githubusercontent.com/13085858/192848040-eefd35e9-2e52-49f0-b1d7-62ec2465866e.png">

**Comment by tlehletmt** [comment]
Yes that was the problem. I have now changed this and the login works now. Thank you very much for the quick help!
