### ISSUE TITLE
Could not read config: open ./config.json: no such file or directory

### ISSUE THREAD

**Issue by poweryu** [virtualzone/onedrive-uploader#17]
I installed onedrive-uploader, config.json and secret.json in `/home/user/.local/bin/` directory, it works fine in this directory,and when I run them in other directories, it will prompt：Could not read config: open ./config.json: no such file or directory.

onedrive-uploader version：0.50
system： Debian arm 5.15

![ddddd](https://user-images.githubusercontent.com/3372681/193548092-ce0dca63-cc1d-4161-82d2-a739d9194535.png)

**Comment by poweryu** [comment]
![ddddd](https://user-images.githubusercontent.com/3372681/193547981-f6ad1eb3-05b6-4a84-9738-bfc8d221a0af.png)

**Comment by virtualzone** [comment]
@poweryu In version 0.5.1, OneDrive Uploader uses the config.json from the current working directory. You can change that behaviour by specifying the path to your config.json using the "-c" parameter, i.e.:

```onedrive-uploader -c /path/to/config.json <command>```

**Comment by poweryu** [comment]
Is it possible to fill in Secret and save it to the .config directory automatically, like github's cli gh, so that you don't need to specify the "-c" parameter to run it in other directories?

**Comment by virtualzone** [comment]
That's a good idea. I'll look into that.

**Comment by poweryu** [comment]
Thank you!

**Comment by virtualzone** [comment]
@poweryu Version 0.6.0 which I just released stores the configuration file in the current user's config directory (i.e. ```.config``` on Linux).
