### ISSUE TITLE
Unable ro build at arm device

### ISSUE THREAD

**Issue by ljc-fight** [virtualzone/onedrive-uploader#2]
This is the log
-----
root@localhost:~/onedrive-uploader# make
rm -f build/*
echo "package main\n\nvar AppVersion = \"`cat ./VERSION | awk NF`\"" > version.go
env GOOS=linux GOARCH=amd64 go build -o build/onedrive-uploader_linux_amd64_`cat ./VERSION | awk NF`
env: ‘go’: No such file or directory
make: *** [Makefile:18: linux_amd64] Error 127
-----
Could you please make it possible on arm device?

**Comment by virtualzone** [comment]
Do you have Go installed?
