### ISSUE TITLE
Add support for golang library

### ISSUE THREAD

**Issue by fireinrain** [virtualzone/onedrive-uploader#24]
As the title said, I can i use this lib in my personal project?

**Comment by virtualzone** [comment]
Hi @fireinrain , yes, according to the project’s MIT license.

**Comment by fireinrain** [comment]
> Hi @fireinrain , yes, according to the project’s MIT license.

I mean Is there a way to use this lib in other golang project as a golang library.
does I need wrap with this in exec.Command(“onedrive-uploader”,"other args")
or I can use import onedrive-uploader and xxx.uploadfile()

**Comment by virtualzone** [comment]
You can use the lib contained in the "sdk" folder.

**Comment by fireinrain** [comment]
> You can use the lib contained in the "sdk" folder.

thanks, I get it.
