### ISSUE TITLE
Personal OneDrive usage?

### ISSUE THREAD

**Issue by WatersJohn** [virtualzone/onedrive-uploader#25]
Not an issue, but a question: Given the prerequisite to create an AAD application, I'm assuming this tool is intended for OneDrive for Business.  Is it possible to adapt this for a personal OneDrive account? (i.e. you're a home user who has licensed O365, but don't have your own AAD tenant).

Thanks - this tool looks very useful, much more reliable to upload files en masse than the browser based approach.

**Comment by virtualzone** [comment]
Hi @WatersJohn, I'm using it with my personal OneDrive account. The necessity to create an AAD application is just a means for OneDrive Uploader being able to authenticate with your OneDrive account.
