### ISSUE TITLE
Missing instructions on how to upload to the App Folder

### ISSUE THREAD

**Issue by vitorsouza** [virtualzone/onedrive-uploader#31]
Hello, thanks for the tool.

I followed the instructions on the README, giving permission only to the App Folder. Any command that I issue gets me an access denied message, for instance:

```
% onedrive-uploader ls /
Could not list: received unexpected status code 403: Access denied (accessDenied)
```

I suppose I should point to the App Folder, but I don't know what that is and couldn't find instructions about this. In my OneDrive, an `Apps` (actually `Aplicativos` because it's in Brazilian Portuguese) folder was created automatically, but there's nothing inside it. I tried creating an `onedrive-uploader` folder inside it to access that, but still access denied. I tried `mkdir` and `upload` but they all get status code 403.

The [documentation from Microsoft](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/special-folders-appfolder?view=odsp-graph-online) mentions a special folder namespace, but that doesn't work either (I guess it works only if used in the REST API calls within onedrive-uploader)...

If it helps to know, in the `onedrive-uploader config` process, I chose options:

```
Available scopes:
1) Default (Files.Read, Files.ReadWrite, Files.Read.All, Files.ReadWrite.All, offline_access)
2) App Root (Files.ReadWrite.AppFolder, offline_access)
3) Custom
Select Scopes [1]: 2
Available Drive Roots:
1) Default (/drive/root)
2) App Root (/drive/special/approot)
3) Custom
Select Drive Root [1]: 2
```

Appreciate if you could help me with this. Thanks!

**Comment by vitorsouza** [comment]
Update: I was trying the upload on my work Microsoft account (managed by my university). I performed the login on my personal Microsoft account and it worked. The `Apps/onedrive-uploader` folder was created and I was able to upload a file. There's probably some constraint on my work account that prevents it from working.

Anyways, I'll close the issue as there is no need for instructions on how to upload to the App folder. It sets it as root internally.

**Comment by jontywigster** [comment]
Hello,

I know this issue is closed (sorry!) but in case anyone else comes across this issue:

> The Files.ReadWrite.AppFolder delegated permission is only valid for personal accounts

[https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/permissions_reference?view=odsp-graph-online](https://learn.microsoft.com/en-us/onedrive/developer/rest-api/concepts/permissions_reference?view=odsp-graph-online)

Cheers
