### ISSUE TITLE
Upload speed much lower than via the browser

### ISSUE THREAD

**Issue by martinsotirov** [virtualzone/onedrive-uploader#32]
Is it possible that Microsoft imposes some bandwidth limitations to the Azure app that we use to connect onedrive-uploader? I can never get more than about 300 kB/s while via the browser I can upload with multiple MB/s.

**Comment by virtualzone** [comment]
Same issue here... Not a big issue for me, as I'm using OneDrive uploader to upload backups via cronjobs, so no need to wait for the upload to finish.
If anyone has an idea on how to improve upload speeds, please let me know.

**Comment by northboys** [comment]
File path: sdk/upload.go
```
var (
	UploadSessionFileSizeLimit int = 10 * 1024 * 1024 // 10 MB
	UploadSessionMultiple      int = 320 * 1024       // 320 KB
)

```

Can this variable be made custom?
```
example:
onedrive-uploader upload /tmp/image.jpg test --upload-speed-limit=1MB --upload-size-limit=10GB
```
