### ISSUE TITLE
Segmentation Violation Error in High Usage Enviornment (ARM64/x86)

### ISSUE THREAD

**Issue by OttomanZ** [virtualzone/onedrive-uploader#40]
![image](https://github.com/user-attachments/assets/ef864f25-c595-4040-a105-927d4480481e)

Hi @virtualzone ,

First of all I have to say this, `onedrive-uploader` is an awesome project we have ended up using in so many of our own projects, and we are really thankful for the great work you are doing here. You've done an amazing job. 

## Issue Description 

 Now to the point here in question, I have an extremely intensive project that uploads `20-30 documents` per minute using `onedrive-uploader` and every once in a while after 5-6 hours it will have this error on one of the files and then `onedrive-uploader` gets back to normal. This Segmentation Violation is occurring due to a memory leak which is very hard to get in say a low usage environment.

## Testing Environment

*OS*: Ubuntu 20.04 LTS
*Platform*: Same Issue on ARM & x86
*Internet Connection*: 2 Gigabit on a Cloud Platform

## How to Replicate

Consistently Upload Documents for a Couple of Hours without Rebooting and eventually you should see this Segmentation Violation. I have tested this out on vanilla Ubuntu 20.04 installs. 

  
## Conclusion

I don't know if the above attached traceback could help us pin-point the leak at hand it `main.go:147` so if we can add an exception handle for that `invalid memory address or nil` we can fix the issue.

**Comment by virtualzone** [comment]
Hi @OttomanZ ,
thanks for your bug report! I've hopefully found the cause of this segfault, however not the cause of the failing upload. Nevertheless, the segfault should be fixed with version 0.8.2. I'd be happy to hear if this resolves your issue.

**Comment by OttomanZ** [comment]
Hey @virtualzone my testing shows your update has successfully fixed this issue, you can close this.
