### ISSUE TITLE
How Long can the Token be used until it can be refreshed.

### ISSUE THREAD

**Issue by OttomanZ** [virtualzone/onedrive-uploader#6]
So, I'm using this fantastic command-line tool in a project where time is of the essence, and hence we need to upload all of the files and then delete them from our server. My question is when is this token going to expire.

**Comment by virtualzone** [comment]
Thanks for your feedback @OttomanZ !

Before executing any command (like uploading a file), the tool checks if the access token needs to be renewed. If this is the case, it uses the refresh token to renew it. Afterwards, the actual command is executed. The access token expires after 60 minutes according to Microsoft's docs.

So, if you're using a shell script with a loop to upload the files, and upload one file at once, you should not run into issues. However, try and validate this before actually deleting the files from the server.

**Comment by OttomanZ** [comment]
Thanks.
